---
translations:
  - file: app/javascript/locales/:locale.json
    patterns:
      - "*"
      - "!*.activerecord.*"
      - "!*.errors.*"
      - "!*.number.nth"
      - "!*.devise.*"
      - "!*.faker.*"
